### ISSUE TITLE
v3 issues

### ISSUE THREAD

**Issue by vdineva** [xrutayisire/react-js-cron#41] opened 2022-11-28 15:13 UTC
**Describe the bug**
Getting the following errors when upgrading to v5 of `react-js-cron`

**Screenshots**

*** App build ***
![Screenshot 2022-11-28 at 10 12 38](https://user-images.githubusercontent.com/791418/204313058-9417d868-aae0-43b4-a864-c43db205de9a.png)

***Unit tests***
![Screenshot 2022-11-28 at 10 08 02](https://user-images.githubusercontent.com/791418/204312255-eaa10f70-bb17-4034-be4b-e31f0f1c8873.png)

**Versions (please complete the following information):**
 - react-js-cron version 3.0.0
 - Ant Design version: 5.0.0 (also tried with 5.0.2)
 - React version: 17.0.2

**Comment by xrutayisire** [comment] 2022-11-28 15:15
Ouch! Thanks for the bug report!

I surely did something wrong with last v3.0.0 version for antd v5.

I will try to find a fix! Stay tuned!

**Comment by xrutayisire** [comment] 2022-11-29 10:54
New release v3.0.1 is out! 🚀

Please test it and let me know if it's all good for you, I close the issue, but you can reopen it if you have any problem with the new build.

**Comment by vdineva** [comment] 2022-11-29 14:00
@xrutayisire Thank you for the quick turnaround on this issue.
I'm still seeing errors though with v3.0.1 of `react-js-cron` and v5.0.2 of `antd`:

![Screenshot 2022-11-29 at 8 57 31](https://user-images.githubusercontent.com/791418/204548721-f8c9af83-70eb-435d-8bf4-356a34eb1ffe.png)

**Comment by xrutayisire** [comment] 2022-11-29 14:15
So strange, I created a small code sandbox to check the new release and it's working with v3.0.1 but not with old v3.0.0.

Link: https://codesandbox.io/s/test-release-react-js-cron-814ylc?file=/src/App.tsx

Can you give me a reproducible repository or a code sandbox so I can understand how this happen?

**Comment by vdineva** [comment] 2022-11-29 14:45
Interesting - one thing I noticed is that the codesandbox uses v18 of React and we're locked in at v17 - maybe that's what it is? Will try to take a deeper look today

**Comment by xrutayisire** [comment] 2022-11-29 16:35
Tested with react 17 and it's working, with antd 4.23.0 (minimal supported version) or v5.0.2

Link: https://codesandbox.io/s/test-release-react-js-cron-min-versions-6bb0cz?file=/src/App.tsx

I will update info about minimal required version because react 16.8.0 is too old now for me to support.

**Comment by xrutayisire** [comment] 2022-12-06 16:28
Without any activity, I'm closing this thread. Don't hesitate to reply again here with a reproducible repo and I reopen the issue.

**Closed by xrutayisire** 2022-12-06 16:28 UTC
Labels: bug
