### ISSUE TITLE
Remove Antd dependency?

### ISSUE THREAD

**Issue by fab-mindflow** [xrutayisire/react-js-cron#43] opened 2023-01-18 14:35 UTC
**Is your feature request related to a problem? Please describe.**
Antd looks required and the bundle is more than 56mb.

**Describe the solution you'd like**
Same great module without antd dependency, or only what is required i.e a lot more lightweight.

**Describe alternatives you've considered**
Custom dev. Fork. Migration to Material UI. Any other OSS project (we haven't found)?

**Additional context**
The component is quite appealing. We'd love to get feedback and possibly help.

**Comment by Zuxaw-flow** [comment] 2023-01-18 15:37
We found this https://github.com/baymac/material-ui-cron in your PR's list the visual is not the same but it works for us

**Comment by xrutayisire** [comment] 2023-01-19 23:25
Hello,

Duplicate of https://github.com/xrutayisire/react-js-cron/issues/10.

It could be nice of course to have this component work with any library or no library at all. I don't have the time to handle this at the moment, but it would be great if someone can help on that.

I propose you continue the conversation on the other issue if you can help on that.

**Closed by xrutayisire** 2023-01-19 23:25 UTC
